// Admin section registry + bilingual labels for the Swiss Blue content panel.
import type { AdminSection, AdminSectionTranslation, JsonObject, Language } from "./types";

export const languages: Record<Language, { label: string; short: string; previewHref: string }> = {
  en: { label: "English", short: "EN", previewHref: "/en" },
  ar: { label: "العربية", short: "AR", previewHref: "/ar" },
};

export const adminSections: AdminSection[] = [
  {
    id: "navGroups",
    group: "Site-wide",
    label: "Navigation",
    description: "Main menu groups, dropdown labels, and page links.",
    path: ["navGroups"],
  },
  {
    id: "media",
    group: "Site-wide",
    label: "Website photos",
    description: "Logo, the three hero slides, city photos, and shared images.",
    path: ["media"],
  },
  {
    id: "hospitalityGallery",
    group: "Site-wide",
    label: "Hospitality gallery",
    description: "Homepage hospitality gallery photos and captions.",
    path: ["media", "gallery"],
  },
  {
    id: "footerSections",
    group: "Site-wide",
    label: "Footer links",
    description: "Footer columns and supporting site links.",
    path: ["footerSections"],
  },
  {
    id: "footerContact",
    group: "Site-wide",
    label: "Footer support",
    description: "Support bullets shown beside the footer booking action.",
    path: ["footerContact"],
  },
  {
    id: "footerMeta",
    group: "Site-wide",
    label: "Footer text",
    description: "Footer description, city badges, support heading, contact button, and copyright lines.",
    path: ["footerMeta"],
  },
  {
    id: "uiText",
    group: "Site-wide",
    label: "Site-wide UI text",
    description: "Book button, booking bar labels, mobile menu, payment label, and cookie banner copy.",
    path: ["ui"],
  },
  {
    id: "closingCtas",
    group: "Site-wide",
    label: "Closing CTAs (page bottoms)",
    description: "The booking call-to-action band at the bottom of every page: shared eyebrow + body text, and each page's title and button.",
    path: ["closingCtas"],
  },
  {
    id: "hero",
    group: "Homepage",
    label: "Hero & booking",
    description: "Main banner headline, supporting copy, and primary actions.",
    path: ["homepage", "hero"],
  },
  {
    id: "highlights",
    group: "Homepage",
    label: "Key numbers",
    description: "The four statistics displayed under the hero section.",
    path: ["homepage", "highlights"],
  },
  {
    id: "properties",
    group: "Homepage",
    label: "Property cards",
    description: "The six hospitality property cards shown on the homepage.",
    path: ["homepage", "properties"],
  },
  {
    id: "loyalty",
    group: "Homepage",
    label: "Loyalty program",
    description: "Program headline, intro text, and guest benefits.",
    path: ["homepage", "loyalty"],
  },
  {
    id: "destinations",
    group: "Homepage",
    label: "Destinations",
    description: "Jeddah, Riyadh, and Jazan cards and city guidance.",
    path: ["homepage", "destinations"],
  },
  {
    id: "offers",
    group: "Homepage",
    label: "Offers",
    description: "Business, family, and monthly-stay offer blocks.",
    path: ["homepage", "offers"],
  },
  {
    id: "services",
    group: "Homepage",
    label: "Services",
    description: "Service section text and amenity list.",
    path: ["homepage", "services"],
  },
  {
    id: "categories",
    group: "Homepage",
    label: "Stay categories",
    description: "Hotel, apart-hotel, and serviced-apartment comparison.",
    path: ["homepage", "categories"],
  },
  {
    id: "testimonials",
    group: "Homepage",
    label: "Guest testimonials",
    description: "Reviews shown on the homepage. Pull real testimonials from Google Maps, Booking.com, Agoda, Expedia, and other platforms.",
    path: ["homepage", "testimonials"],
  },
  {
    id: "cta",
    group: "Homepage",
    label: "Closing CTA",
    description: "Final booking call-to-action at the bottom of the page.",
    path: ["homepage", "cta"],
  },
  {
    id: "homepageFaq",
    group: "Homepage",
    label: "Homepage FAQ",
    description: "Questions shown near the bottom of the homepage.",
    path: ["faq", "homepage"],
  },
  {
    id: "hotelsSubpage",
    group: "Stay",
    label: "Hotels page",
    description: "Hotels page hero and introduction text.",
    path: ["subpages", "hotelsPage"],
  },
  {
    id: "roomsSuitesPage",
    group: "Stay",
    label: "Rooms & Suites page",
    description: "Rooms page hero, classification principles, table intro, and classifications table.",
    path: ["subpages", "roomsSuites"],
  },
  {
    id: "servicedApartmentsPage",
    group: "Stay",
    label: "Serviced Apartments page",
    description: "Serviced Apartments page hero banner.",
    path: ["subpages", "servicedApartments"],
  },
  {
    id: "amenitiesServicesPage",
    group: "Stay",
    label: "Amenities & Services page",
    description: "Amenities & Services page hero banner.",
    path: ["subpages", "amenitiesServices"],
  },
  {
    id: "propertyFaq",
    group: "Stay",
    label: "Property FAQ",
    description: "Questions shown on every hotel detail page.",
    path: ["faq", "property"],
  },
  {
    id: "destinationsSubpage",
    group: "Experience",
    label: "Destinations page",
    description: "Destinations page hero banner.",
    path: ["subpages", "destinationsPage"],
  },
  {
    id: "diningPage",
    group: "Experience",
    label: "Dining page",
    description: "Dining page hero banner, introduction text, and food services list.",
    path: ["subpages", "dining"],
  },
  {
    id: "offersSubpage",
    group: "Offers",
    label: "Offers page",
    description: "Offers page hero, main offers, and booking benefits lists.",
    path: ["subpages", "offersPage"],
  },
  {
    id: "loyaltySubpage",
    group: "Offers",
    label: "Loyalty page",
    description: "Loyalty page hero banner.",
    path: ["subpages", "loyaltyPage"],
  },
  {
    id: "corporateDealsSubpage",
    group: "Business",
    label: "Corporate Deals page",
    description: "Corporate Deals page hero banner.",
    path: ["subpages", "corporateDealsPage"],
  },
  {
    id: "b2bForm",
    group: "Business",
    label: "B2B — request form",
    description: "Corporate (B2B) request form: intro, step headings, every field label, and dropdown options.",
    path: ["subpages", "corporateDealsPage", "requestForm"],
  },
  {
    id: "meetingsEventsPage",
    group: "Business",
    label: "Meetings & Events page",
    description: "Meetings page hero, intro, documents, and corporate deal features.",
    path: ["subpages", "meetingsEvents"],
  },
  {
    id: "groupBookingsPage",
    group: "Business",
    label: "Group Bookings page",
    description: "Group Bookings page hero, introduction text, and requirements list.",
    path: ["subpages", "groupBookings"],
  },
  {
    id: "careersSubpage",
    group: "Community",
    label: "Careers page",
    description: "Hero, why-join cards, departments, and apply panel.",
    path: ["subpages", "careersPage"],
  },
  {
    id: "careersForm",
    group: "Community",
    label: "Careers — jobs & application form",
    description: "Workplace culture cards, the job openings list, and the application form labels and messages.",
    path: ["subpages", "careersPage", "recruitment"],
  },
  {
    id: "csrSubpage",
    group: "Community",
    label: "Social Responsibility page",
    description: "Hero, pillars, initiatives, and reporting.",
    path: ["subpages", "csrPage"],
  },
  {
    id: "reservationOfficeSubpage",
    group: "Contact Us",
    label: "Central Reservation page",
    description: "Hero, channels (phone / WhatsApp / email), services, and benefits.",
    path: ["subpages", "reservationOfficePage"],
  },
  {
    id: "feedbackSubpage",
    group: "Contact Us",
    label: "Complaints & Suggestions page",
    description: "Hero, channels, process steps, categories, and escalation path.",
    path: ["subpages", "feedbackPage"],
  },
  {
    id: "contactPage",
    group: "Contact Us",
    label: "Contact page",
    description: "Contact page hero, channels lists, and direct booking intro.",
    path: ["subpages", "contact"],
  },
  {
    id: "aboutPage",
    group: "Company",
    label: "About page",
    description: "About page hero banner, philosophy paragraph, and brand pillars.",
    path: ["subpages", "about"],
  },
  {
    id: "faqSubpage",
    group: "Company",
    label: "FAQ page",
    description: "FAQ page hero banner.",
    path: ["subpages", "faqPage"],
  },
  {
    id: "faqCategories",
    group: "Company",
    label: "Full FAQ page",
    description: "FAQ categories and questions shown on the full FAQ page.",
    path: ["faq", "categories"],
  },
];

export const arabicSectionLabels: Record<string, AdminSectionTranslation> = {
  navGroups: {
    group: "إعدادات الموقع",
    label: "القائمة الرئيسية",
    description: "مجموعات القائمة، عناوين القوائم المنسدلة، وروابط الصفحات.",
  },
  media: {
    group: "إعدادات الموقع",
    label: "صور الموقع",
    description: "الشعار، شرائح البانر الثلاث، صور المدن، والصور المشتركة.",
  },
  hospitalityGallery: {
    group: "إعدادات الموقع",
    label: "معرض الضيافة",
    description: "صور معرض الضيافة في الصفحة الرئيسية وعناوينها.",
  },
  footerSections: {
    group: "إعدادات الموقع",
    label: "روابط الفوتر",
    description: "أعمدة الفوتر وروابط الموقع المساندة.",
  },
  footerContact: {
    group: "إعدادات الموقع",
    label: "دعم الفوتر",
    description: "نقاط الدعم المعروضة بجانب زر الحجز في الفوتر.",
  },
  footerMeta: {
    group: "إعدادات الموقع",
    label: "نصوص الفوتر",
    description: "وصف الفوتر، شارات المدن، عنوان الدعم، زر التواصل، وسطور حقوق النشر.",
  },
  uiText: {
    group: "إعدادات الموقع",
    label: "نصوص واجهة الموقع",
    description: "زر الحجز، تسميات شريط الحجز، قائمة الجوال، نص الدفع، ونص لافتة الكوكيز.",
  },
  closingCtas: {
    group: "إعدادات الموقع",
    label: "نداءات الإجراء الختامية",
    description: "شريط الحجز أسفل كل صفحة: العنوان الفرعي والنص المشترك، وعنوان وزر كل صفحة.",
  },
  hero: {
    group: "الصفحة الرئيسية",
    label: "البانر والحجز",
    description: "عنوان البانر الرئيسي، النص المساند، وأزرار الإجراء.",
  },
  highlights: {
    group: "الصفحة الرئيسية",
    label: "الأرقام الرئيسية",
    description: "الأرقام الأربعة المعروضة أسفل البانر.",
  },
  properties: {
    group: "الصفحة الرئيسية",
    label: "بطاقات الفنادق",
    description: "بطاقات منشآت الضيافة المعروضة في الصفحة الرئيسية.",
  },
  loyalty: {
    group: "الصفحة الرئيسية",
    label: "برنامج الولاء",
    description: "عنوان البرنامج، النص التعريفي، ومزايا الضيوف.",
  },
  destinations: {
    group: "الصفحة الرئيسية",
    label: "الوجهات",
    description: "بطاقات جدة والرياض وجازان ومحتوى المدن.",
  },
  offers: {
    group: "الصفحة الرئيسية",
    label: "العروض",
    description: "محتوى عروض الأعمال والعائلات والإقامات الشهرية.",
  },
  services: {
    group: "الصفحة الرئيسية",
    label: "الخدمات",
    description: "نص قسم الخدمات وقائمة المرافق.",
  },
  categories: {
    group: "الصفحة الرئيسية",
    label: "فئات الإقامة",
    description: "مقارنة الفندق والشقق الفندقية والشقق المخدومة.",
  },
  testimonials: {
    group: "الصفحة الرئيسية",
    label: "آراء الضيوف",
    description: "آراء حقيقية من ضيوفنا عبر جوجل، Booking.com، Agoda، Expedia وغيرها.",
  },
  cta: {
    group: "الصفحة الرئيسية",
    label: "دعوة الإجراء الختامية",
    description: "دعوة الحجز في نهاية الصفحة.",
  },
  homepageFaq: {
    group: "الصفحة الرئيسية",
    label: "أسئلة الصفحة الرئيسية",
    description: "الأسئلة المعروضة قرب نهاية الصفحة الرئيسية.",
  },
  hotelsSubpage: {
    group: "الإقامة",
    label: "صفحة الفنادق والوجهات",
    description: "بانر صفحة الفنادق والنص التعريفي المساعد.",
  },
  roomsSuitesPage: {
    group: "الإقامة",
    label: "صفحة الغرف والأجنحة",
    description: "بانر صفحة الغرف، مبادئ التصنيف، مقدمة الجدول، وجدول التصنيفات المعتمد.",
  },
  servicedApartmentsPage: {
    group: "الإقامة",
    label: "صفحة الشقق الفندقية",
    description: "بانر صفحة الشقق الفندقية والخيارات المتاحة.",
  },
  amenitiesServicesPage: {
    group: "الإقامة",
    label: "صفحة الخدمات والمرافق",
    description: "بانر صفحة الخدمات والمرافق الأساسية للضيوف.",
  },
  propertyFaq: {
    group: "الإقامة",
    label: "أسئلة صفحات الفنادق",
    description: "الأسئلة المعروضة في كل صفحة فندق.",
  },
  destinationsSubpage: {
    group: "التجربة",
    label: "صفحة المدن والوجهات",
    description: "بانر صفحة وجهات سويس بلو والمدن الرئيسية.",
  },
  diningPage: {
    group: "التجربة",
    label: "صفحة الطعام",
    description: "بانر صفحة الطعام، النص التعريفي، وقائمة خدمات الطعام.",
  },
  offersSubpage: {
    group: "العروض",
    label: "صفحة العروض",
    description: "بانر صفحة العروض، العروض الرئيسية، ومزايا الحجز المباشر.",
  },
  loyaltySubpage: {
    group: "العروض",
    label: "صفحة برنامج الولاء",
    description: "بانر صفحة برنامج الولاء والمزايا المباشرة للضيوف.",
  },
  corporateDealsSubpage: {
    group: "الأعمال",
    label: "صفحة تعاقدات الشركات",
    description: "بانر صفحة تعاقدات الشركات والتعريف بالحلول.",
  },
  b2bForm: {
    group: "الأعمال",
    label: "نموذج طلب الشركات",
    description: "نموذج طلب الشركات: التمهيد، عناوين الخطوات، تسميات الحقول، وخيارات القوائم المنسدلة.",
  },
  meetingsEventsPage: {
    group: "الأعمال",
    label: "صفحة الاجتماعات والمناسبات",
    description: "بانر صفحة الاجتماعات، النص التعريفي، المستندات، ومزايا صفقات الشركات.",
  },
  groupBookingsPage: {
    group: "الأعمال",
    label: "صفحة حجوزات المجموعات",
    description: "بانر صفحة حجوزات المجموعات، النص التعريفي، وقائمة المتطلبات.",
  },
  careersSubpage: {
    group: "المجتمع",
    label: "صفحة الوظائف",
    description: "البانر، بطاقات لماذا الانضمام، الأقسام، ولوحة التقديم.",
  },
  careersForm: {
    group: "المجتمع",
    label: "الوظائف ونموذج التقديم",
    description: "بطاقات ثقافة العمل، قائمة الوظائف المتاحة، وتسميات ورسائل نموذج التقديم.",
  },
  csrSubpage: {
    group: "المجتمع",
    label: "صفحة المسؤولية الاجتماعية",
    description: "البانر، الركائز، المبادرات، والشفافية.",
  },
  reservationOfficeSubpage: {
    group: "تواصل معنا",
    label: "صفحة مكتب الحجوزات المركزي",
    description: "البانر، قنوات التواصل (هاتف / واتساب / بريد)، الخدمات، والميزات.",
  },
  feedbackSubpage: {
    group: "تواصل معنا",
    label: "صفحة الشكاوى والاقتراحات",
    description: "البانر، قنوات الاستلام، خطوات المعالجة، الفئات، ومسار التصعيد.",
  },
  contactPage: {
    group: "تواصل معنا",
    label: "صفحة اتصل بنا",
    description: "بانر صفحة اتصل بنا، قنوات الاتصال، ومقدمة الحجز المباشر.",
  },
  aboutPage: {
    group: "عن الشركة",
    label: "صفحة من نحن",
    description: "بانر صفحة من نحن، فقرة الفلسفة، وركائز العلامة التجارية.",
  },
  faqSubpage: {
    group: "عن الشركة",
    label: "صفحة الأسئلة الشائعة",
    description: "بانر صفحة الأسئلة الشائعة والمعلومات المساعدة.",
  },
  faqCategories: {
    group: "عن الشركة",
    label: "صفحة الأسئلة الشائعة الكاملة",
    description: "تصنيفات الأسئلة والأسئلة المعروضة في صفحة الأسئلة الشائعة الكاملة.",
  },
};

export const fieldLabels: Record<string, string> = {
  defaultText: "Default body text",
  pages: "Per-page CTAs",
  hotelDetail: "Hotel detail page",
  titleTemplate: "Title template ({hotel} = hotel name)",
  bookNow: "Book button",
  bookingBar: "Booking bar labels",
  mobileNav: "Mobile menu labels",
  payments: "Payment label",
  cookie: "Cookie banner",
  accept: "Accept button",
  decline: "Decline button",
  policy: "Policy link text",
  aria: "Accessibility label",
  checkin: "Check-in label",
  checkout: "Check-out label",
  guests: "Guests label",
  culture: "Workplace culture",
  openingsIntro: "Job openings intro",
  jobs: "Job openings",
  applyLabels: "Apply section labels",
  applyForm: "Application form fields",
  responsibilities: "Responsibilities",
  qualifications: "Qualifications",
  experience: "Experience",
  skills: "Skills",
  fields: "Field labels",
  placeholders: "Field placeholders",
  steps: "Steps list",
  note: "Note",
  success: "Success message",
  sectorOptions: "Sector options",
  cityOptions: "City options",
  propertyTypeOptions: "Property type options",
  requestTypeOptions: "Request type options",
  documentsOptions: "Documents options",
  contactOptions: "Contact method options",
  cityBadges: "City badges",
  supportHeading: "Support heading",
  contactCta: "Contact button",
  tagline: "Footer tagline",
  amenities: "Amenities",
  applyIntro: "Apply panel",
  benefits: "Benefits",
  careersPage: "Careers page",
  categories: "Categories",
  categoriesIntro: "Categories intro",
  csrPage: "Social Responsibility page",
  departments: "Departments",
  departmentsIntro: "Departments intro",
  email: "Email address",
  escalationIntro: "Escalation intro",
  feedbackPage: "Complaints & Suggestions page",
  initiatives: "Initiatives",
  initiativesIntro: "Initiatives intro",
  process: "Process steps",
  reportingIntro: "Reporting intro",
  reservationOfficePage: "Central Reservation page",
  services: "Services",
  servicesIntro: "Services intro",
  whyJoin: "Why join us",
  button: "Button label",
  city: "City",
  count: "Count",
  cta: "Button label",
  description: "Description",
  destination: "Destination label",
  eyebrow: "Small heading",
  faqCategories: "FAQ categories",
  gallery: "Gallery images",
  hero: "Main banner",
  href: "Link URL",
  howToEnjoy: "How to enjoy",
  image: "Photo",
  arabicLogo: "Arabic logo",
  jazan: "Jazan photo",
  jeddah: "Jeddah photo",
  items: "Cards",
  label: "Label",
  landmarks: "Nearby landmarks",
  links: "Links",
  logo: "Logo",
  locationHighlight: "Location highlight",
  mainHero: "Hero fallback photo",
  mainHeroSlides: "Hero photos/videos",
  mapQuery: "Google Maps search",
  media: "Website photos",
  primaryCta: "Primary button",
  positioning: "Positioning paragraph",
  question: "Question",
  secondaryCta: "Secondary button",
  secondaryHref: "Secondary button URL",
  slug: "Page slug",
  source: "Source URL",
  platform: "Booking platform",
  quote: "Review quote",
  rating: "Rating (1–5)",
  role: "Stay type",
  name: "Guest name",
  kind: "Media type",
  summary: "Short summary",
  text: "Body text",
  title: "Title",
  type: "Type",
  unitTypes: "Unit types",
  units: "Unit count",
  value: "Value",
  philosophy: "Brand philosophy",
  pillars: "Brand pillars",
  intro: "Introduction",
  options: "Food services list",
  principles: "Principles",
  detailsIntro: "Details introduction",
  classifications: "Classifications list",
  property: "Property",
  rows: "Table rows",
  bedrooms: "Bedrooms",
  bedConfig: "Bed configuration",
  view: "View",
  bathrooms: "Bathrooms",
  livingRooms: "Living rooms",
  totalUnits: "Total units count",
  rooms: "Room numbers",
  deals: "Corporate deals feature",
  documentsIntro: "Documents intro",
  documents: "Required documents",
  channels: "Contact channels",
  bookingIntro: "Booking panel intro",
  offers: "Offers list",
  benefitsIntro: "Direct booking intro",
};

export const arabicFieldLabels: Record<string, string> = {
  defaultText: "النص الافتراضي",
  pages: "نداءات كل صفحة",
  hotelDetail: "صفحة تفاصيل الفندق",
  titleTemplate: "قالب العنوان ({hotel} = اسم الفندق)",
  bookNow: "زر الحجز",
  bookingBar: "تسميات شريط الحجز",
  mobileNav: "تسميات قائمة الجوال",
  payments: "نص الدفع",
  cookie: "لافتة الكوكيز",
  accept: "زر القبول",
  decline: "زر الرفض",
  policy: "نص رابط السياسة",
  aria: "تسمية الوصول",
  checkin: "تسمية الوصول",
  checkout: "تسمية المغادرة",
  guests: "تسمية الضيوف",
  culture: "ثقافة العمل",
  openingsIntro: "تمهيد الوظائف",
  jobs: "الوظائف المتاحة",
  applyLabels: "تسميات قسم التقديم",
  applyForm: "حقول نموذج التقديم",
  responsibilities: "المسؤوليات",
  qualifications: "المؤهلات",
  experience: "الخبرة",
  skills: "المهارات",
  fields: "تسميات الحقول",
  placeholders: "النصوص التوضيحية",
  steps: "قائمة الخطوات",
  note: "ملاحظة",
  success: "رسالة النجاح",
  sectorOptions: "خيارات القطاع",
  cityOptions: "خيارات المدينة",
  propertyTypeOptions: "خيارات نوع المنشأة",
  requestTypeOptions: "خيارات نوع الطلب",
  documentsOptions: "خيارات المستندات",
  contactOptions: "خيارات وسيلة التواصل",
  cityBadges: "شارات المدن",
  supportHeading: "عنوان الدعم",
  contactCta: "زر التواصل",
  tagline: "سطر الفوتر",
  amenities: "المرافق",
  answer: "الإجابة",
  applyIntro: "لوحة التقديم",
  benefits: "المزايا",
  button: "نص الزر",
  careersPage: "صفحة الوظائف",
  categories: "الفئات",
  categoriesIntro: "تقديم الفئات",
  csrPage: "صفحة المسؤولية الاجتماعية",
  departments: "الأقسام",
  departmentsIntro: "تقديم الأقسام",
  email: "البريد الإلكتروني",
  escalationIntro: "تقديم مسار التصعيد",
  feedbackPage: "صفحة الشكاوى والاقتراحات",
  initiatives: "المبادرات",
  initiativesIntro: "تقديم المبادرات",
  process: "خطوات المعالجة",
  reportingIntro: "تقديم الشفافية",
  reservationOfficePage: "صفحة مكتب الحجوزات المركزي",
  services: "الخدمات",
  servicesIntro: "تقديم الخدمات",
  whyJoin: "لماذا الانضمام",
  city: "المدينة",
  count: "العدد",
  cta: "نص الزر",
  description: "الوصف",
  destination: "نص الوجهة",
  eyebrow: "العنوان الصغير",
  faqCategories: "تصنيفات الأسئلة الشائعة",
  gallery: "صور المعرض",
  hero: "البانر الرئيسي",
  href: "رابط الصفحة",
  howToEnjoy: "طريقة الاستفادة",
  image: "الصورة",
  arabicLogo: "الشعار العربي",
  jazan: "صورة جازان",
  jeddah: "صورة جدة",
  items: "البطاقات",
  label: "التسمية",
  landmarks: "المعالم القريبة",
  links: "الروابط",
  logo: "الشعار",
  locationHighlight: "ميزة الموقع",
  mainHero: "صورة احتياطية للبانر",
  mainHeroSlides: "صور وفيديوهات البانر",
  mapQuery: "بحث خرائط Google",
  media: "صور الموقع",
  primaryCta: "الزر الرئيسي",
  positioning: "نص التمركز",
  question: "السؤال",
  secondaryCta: "الزر الثانوي",
  secondaryHref: "رابط الزر الثانوي",
  slug: "رابط الصفحة المختصر",
  source: "رابط الملف",
  platform: "منصة الحجز",
  quote: "نص الرأي",
  rating: "التقييم (1–5)",
  role: "نوع الإقامة",
  name: "اسم الضيف",
  kind: "نوع الملف",
  summary: "الملخص",
  text: "النص",
  title: "العنوان",
  type: "النوع",
  unitTypes: "أنواع الوحدات",
  units: "عدد الوحدات",
  value: "القيمة",
  philosophy: "فلسفة العلامة",
  pillars: "ركائز العلامة",
  intro: "القسم التعريفي",
  options: "خيارات خدمات الطعام",
  principles: "مبادئ التصنيف",
  detailsIntro: "مقدمة تفاصيل الوحدات",
  classifications: "تصنيفات الوحدات",
  property: "المنشأة",
  rows: "صفوف الجدول",
  bedrooms: "غرف النوم",
  bedConfig: "تكوين الأسرّة",
  view: "الإطلالة",
  bathrooms: "دورات المياه",
  livingRooms: "غرف المعيشة",
  totalUnits: "إجمالي الوحدات",
  rooms: "أرقام الغرف",
  deals: "صفقات ومزايا الشركات",
  documentsIntro: "مقدمة المستندات المطلوبة",
  documents: "المستندات المطلوبة",
  channels: "قنوات الاتصال",
  bookingIntro: "مقدمة لوحة الحجز المباشر",
  offers: "قائمة العروض",
  benefitsIntro: "مقدمة مزايا الحجز المباشر",
};

export const fieldOrder = [
  "eyebrow",
  "title",
  "question",
  "answer",
  "text",
  "description",
  "summary",
  "positioning",
  "primaryCta",
  "secondaryCta",
  "secondaryHref",
  "cta",
  "href",
  "button",
  "logo",
  "arabicLogo",
  "mainHero",
  "mainHeroSlides",
  "destination",
  "jeddah",
  "jazan",
  "city",
  "type",
  "units",
  "value",
  "label",
  "slug",
  "image",
  "count",
  "unitTypes",
  "amenities",
  "benefits",
  "locationHighlight",
  "landmarks",
  "mapQuery",
  "gallery",
  "howToEnjoy",
  "links",
  "items",
  "source",
  "kind",
];

export function sectionCopy(section: AdminSection, language: Language) {
  return language === "ar"
    ? arabicSectionLabels[section.id] ?? section
    : section;
}

export function labelFor(key: string, language: Language = "en") {
  if (language === "ar") {
    return arabicFieldLabels[key] ?? fieldLabels[key] ?? key.replace(/([A-Z])/g, " $1");
  }

  return fieldLabels[key] ?? key.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase());
}

export function orderedEntries(object: JsonObject) {
  return Object.entries(object)
    .map(([key, value], index) => ({ key, value, index }))
    .sort((left, right) => {
      const leftOrder = fieldOrder.indexOf(left.key);
      const rightOrder = fieldOrder.indexOf(right.key);
      const leftRank = leftOrder === -1 ? 1000 + left.index : leftOrder;
      const rightRank = rightOrder === -1 ? 1000 + right.index : rightOrder;

      return leftRank - rightRank;
    });
}

export function shouldShowField(path: Array<string | number>, key: string) {
  const isRootMediaField =
    path.length === 2 &&
    (path[0] === "ar" || path[0] === "en") &&
    path[1] === "media";

  if (isRootMediaField && key === "mainHero") {
    return false;
  }

  // Room-number classifications table removed from admin panel — data is no
  // longer surfaced on the property pages so there is nothing to edit here.
  if (key === "classifications" && path.some((p) => p === "roomsSuites")) {
    return false;
  }

  return true;
}


// Structural sections that must always render — hiding them would break the site layout.
export const NON_HIDEABLE_SECTIONS = new Set([
  "navGroups",
  "media",
  "footerSections",
  "footerContact",
  "footerMeta",
  "careersForm",
  "b2bForm",
  "uiText",
  "closingCtas",
]);

